remote_theme: just-the-docs/just-the-docs
title: konsole
description: Documentation for Konsole
baseurl: "/docs" # the subpath of your site, e.g. /blog
color_scheme: dark
url: "https://ooflet.github.io" # the base hostname & protocol for your site, e.g. http://example.com
